# Generated by Django 4.1 on 2022-09-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("member", "member"),
                    ("moderator", "moderator"),
                    ("admin", "admin"),
                ],
                default="member",
                max_length=9,
            ),
        ),
    ]
